### PR TITLE
Mahanthpabba add caption

### PR DESCRIPTION
**Pull request by mahanthpabba**
added my slide changes

### CODE REVIEW

**Comment by jweiaten** [comment]
Too many reviewers. Please change.

**Comment by mahanthpabba** [comment]
> Too many reviewers. Please change.

Done!
review please!

**Comment by jweiaten** [comment]
cannot review anymore :P

**Comment by mahanthpabba** [comment]
> good

**Comment by mahanthpabba** [comment]
> cannot review anymore :P

lets get back to svn then! ;)

**Comment by mahanthpabba** [comment]
Thanks! :)

**Pull request merged**
